import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";
import { format } from "date-fns";

export interface InvoicePdfItemRow {
  itemName?: string;
  hsnCode?: string;
  quantity?: number;
  pricePerItem?: number;
  taxAmount?: number;
  taxPercentage?: number;
  totalAmount?: number;
}

export interface InvoicePdfBusiness {
  businessName?: string;
  name?: string;
  gstin?: string;
  address?: string;
  state?: string;
  logoUrl?: string;
  phone?: string;
  email?: string;
}

export interface InvoicePdfBankAccount {
  bankName?: string;
  accountNumber?: string;
  ifsc?: string;
  upiId?: string;
}

export interface InvoicePdfDocumentProps {
  type: "SALE" | "PURCHASE";
  invoiceNo: string;
  invoiceDate?: string | Date | null;
  dueDate?: string | Date | null;
  partyName: string;
  partyMobile?: string;
  partyGst?: string;
  items: InvoicePdfItemRow[];
  taxable: number;
  tax: number;
  additionalCharges: number;
  discountAfterTax: number;
  total: number;
  paid: number;
  due: number;
  status: string;
  notes?: string;
  termsAndConditions?: string;
  business: InvoicePdfBusiness;
  /** Present only for a generated GST e-Invoice — omitted, this section just doesn't render. */
  eInvoice?: { irn: string; qrDataUrl: string | null };
  /** The business's payout bank account, when one with a UPI ID exists. */
  bankAccount?: InvoicePdfBankAccount;
  /** Pre-rendered "Scan to Pay" UPI QR — generated by the caller (async), not here. */
  paymentQrDataUrl?: string | null;
}

const ACCENT = "#2563eb";
const INK = "#1e293b";
const MUTED = "#64748b";
const BORDER = "#e2e8f0";
const PANEL = "#f8fafc";

const inr = (v: unknown) => `Rs. ${Number(v || 0).toLocaleString("en-IN")}`;
const fmtDate = (v: unknown) => {
  if (!v) return "-";
  const d = new Date(v as string);
  return isNaN(d.getTime()) ? "-" : format(d, "dd MMM yyyy");
};

const STATUS_COLOR: Record<string, { bg: string; fg: string }> = {
  PAID: { bg: "#dcfce7", fg: "#166534" },
  PARTIAL: { bg: "#fef9c3", fg: "#854d0e" },
  UNPAID: { bg: "#fee2e2", fg: "#991b1b" },
  VOID: { bg: "#f1f5f9", fg: "#475569" },
};

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica", color: INK },

  // Header
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  logo: { width: 40, height: 40, objectFit: "contain", marginBottom: 6, borderRadius: 6 },
  businessName: { fontSize: 15, fontWeight: 700, color: INK, marginBottom: 2 },
  muted: { color: MUTED },
  metaLabel: { color: MUTED },
  metaValue: { fontWeight: 700, color: INK },
  pill: {
    backgroundColor: ACCENT,
    color: "#ffffff",
    fontSize: 11,
    fontWeight: 700,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 5,
    alignSelf: "flex-end",
  },
  metaBlock: { marginTop: 8, alignItems: "flex-end" },
  metaRow: { flexDirection: "row", gap: 4, marginTop: 3 },

  divider: { borderBottomWidth: 1, borderBottomColor: BORDER, marginTop: 16, marginBottom: 16 },

  // Two-box row
  boxRow: { flexDirection: "row", gap: 12, marginBottom: 16 },
  box: {
    flex: 1,
    backgroundColor: PANEL,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: BORDER,
  },
  boxLabel: {
    fontSize: 8,
    color: MUTED,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: 700,
    marginBottom: 5,
  },
  boxTitle: { fontSize: 11, fontWeight: 700, color: INK, marginBottom: 2 },

  statusPill: {
    alignSelf: "flex-start",
    fontSize: 9,
    fontWeight: 700,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
    marginBottom: 6,
  },

  // Line items
  sectionHeading: { fontSize: 11, fontWeight: 700, color: INK, marginBottom: 8 },
  table: { borderRadius: 6, overflow: "hidden", borderWidth: 1, borderColor: BORDER },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  tableHeaderText: { fontSize: 8, fontWeight: 700, color: MUTED, textTransform: "uppercase" },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  tableRowAlt: { backgroundColor: "#fafbfc" },
  colItem: { flex: 3 },
  colHsn: { flex: 1.1 },
  colQty: { flex: 0.7, textAlign: "right" },
  colPrice: { flex: 1.1, textAlign: "right" },
  colTax: { flex: 1.2, textAlign: "right" },
  colAmount: { flex: 1.3, textAlign: "right" },

  // Summary
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 12,
  },

  bottomRow: { flexDirection: "row", gap: 12, alignItems: "flex-start" },
  paymentBox: {
    flex: 1,
    backgroundColor: PANEL,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: BORDER,
  },
  paymentRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 4 },
  qrImage: { width: 68, height: 68, marginTop: 8 },

  totalsBox: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 12,
  },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  grandRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 6,
    marginTop: 3,
    borderTopWidth: 1,
    borderTopColor: BORDER,
    fontWeight: 700,
    fontSize: 10.5,
  },
  balanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  balanceLabel: { fontWeight: 700, color: INK },
  balanceValue: { fontWeight: 700, color: ACCENT, fontSize: 12 },

  footerRow: { flexDirection: "row", gap: 24, marginTop: 20 },
  footerCol: { flex: 1 },
  footerHeading: { fontSize: 9, fontWeight: 700, color: INK, marginBottom: 4 },
  footerText: { fontSize: 8, color: MUTED, lineHeight: 1.5 },

  signatureArea: { marginTop: 36, alignItems: "flex-end" },
  signatureLine: { width: 160, borderTopWidth: 1, borderTopColor: INK, paddingTop: 4 },
  signatureLabel: { fontSize: 8, color: MUTED, textAlign: "center" },
});

/**
 * Single source of truth for both the in-app preview (PDFViewer) and the
 * downloaded file (PDFDownloadLink) — same component, same output.
 */
export function InvoicePdfDocument(props: InvoicePdfDocumentProps) {
  const { business } = props;
  const businessName = business.businessName?.trim() || business.name?.trim() || "Your Business";
  const statusColor = STATUS_COLOR[props.status] || STATUS_COLOR.UNPAID;

  // Bottom-left slot: real payout details if we have a bank account with a
  // UPI ID (real "Scan to Pay" QR), else the GST e-Invoice IRN/QR when this
  // invoice has one, else the slot is simply omitted — never fabricated.
  const showPayment = !!(props.bankAccount && props.paymentQrDataUrl);
  const showEInvoice = !showPayment && !!props.eInvoice;

  return (
    <Document title={`Invoice ${props.invoiceNo}`}>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.headerRow}>
          <View>
            {business.logoUrl ? <Image src={business.logoUrl} style={styles.logo} /> : null}
            <Text style={styles.businessName}>{businessName}</Text>
            {business.phone ? <Text style={styles.muted}>{business.phone}</Text> : null}
            {business.email ? <Text style={styles.muted}>{business.email}</Text> : null}
            {business.gstin ? <Text style={styles.muted}>GSTIN: {business.gstin}</Text> : null}
            {business.address ? <Text style={styles.muted}>{business.address}</Text> : null}
            {business.state ? <Text style={styles.muted}>{business.state}</Text> : null}
          </View>
          <View>
            <Text style={styles.pill}>
              {props.type === "SALE" ? "TAX INVOICE" : "PURCHASE BILL"}
            </Text>
            <View style={styles.metaBlock}>
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Invoice No:</Text>
                <Text style={styles.metaValue}>{props.invoiceNo || "-"}</Text>
              </View>
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Date:</Text>
                <Text style={styles.metaValue}>{fmtDate(props.invoiceDate)}</Text>
              </View>
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Due Date:</Text>
                <Text style={styles.metaValue}>{fmtDate(props.dueDate)}</Text>
              </View>
            </View>
          </View>
        </View>

        <View style={styles.divider} />

        {/* Bill To / Status */}
        <View style={styles.boxRow}>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>{props.type === "SALE" ? "Bill To" : "Supplier"}</Text>
            <Text style={styles.boxTitle}>{props.partyName}</Text>
            {props.partyMobile ? <Text style={styles.muted}>{props.partyMobile}</Text> : null}
            {props.partyGst ? <Text style={styles.muted}>GSTIN: {props.partyGst}</Text> : null}
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Payment Status</Text>
            <Text
              style={[
                styles.statusPill,
                { backgroundColor: statusColor.bg, color: statusColor.fg },
              ]}
            >
              {props.status}
            </Text>
            <Text style={styles.muted}>
              {props.type === "SALE" ? "Received" : "Paid"}: {inr(props.paid)}
            </Text>
            <Text style={styles.muted}>Balance Due: {inr(props.due)}</Text>
          </View>
        </View>

        {/* Line items */}
        <Text style={styles.sectionHeading}>Line Items</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderText, styles.colItem]}>Description</Text>
            <Text style={[styles.tableHeaderText, styles.colHsn]}>HSN</Text>
            <Text style={[styles.tableHeaderText, styles.colQty]}>Qty</Text>
            <Text style={[styles.tableHeaderText, styles.colPrice]}>Rate</Text>
            <Text style={[styles.tableHeaderText, styles.colTax]}>Tax</Text>
            <Text style={[styles.tableHeaderText, styles.colAmount]}>Amount</Text>
          </View>
          {props.items.map((row, i) => (
            <View
              style={[styles.tableRow, ...(i % 2 === 1 ? [styles.tableRowAlt] : [])]}
              key={i}
            >
              <Text style={styles.colItem}>{row.itemName || "-"}</Text>
              <Text style={styles.colHsn}>{row.hsnCode || "-"}</Text>
              <Text style={styles.colQty}>{row.quantity ?? 0}</Text>
              <Text style={styles.colPrice}>{inr(row.pricePerItem)}</Text>
              <Text style={styles.colTax}>
                {inr(row.taxAmount)}
                {row.taxPercentage ? ` (${row.taxPercentage}%)` : ""}
              </Text>
              <Text style={styles.colAmount}>{inr(row.totalAmount)}</Text>
            </View>
          ))}
        </View>

        {/* Summary heading */}
        <View style={styles.summaryRow}>
          <Text style={styles.sectionHeading}>Summary</Text>
          <Text style={{ fontSize: 11, fontWeight: 700 }}>Total: {inr(props.total)}</Text>
        </View>

        {/* Payment/e-Invoice box + Totals breakdown */}
        <View style={styles.bottomRow}>
          {showPayment && (
            <View style={styles.paymentBox}>
              <Text style={styles.boxLabel}>Payment Details</Text>
              {props.bankAccount?.bankName ? (
                <View style={styles.paymentRow}>
                  <Text style={styles.muted}>Bank</Text>
                  <Text style={styles.metaValue}>{props.bankAccount.bankName}</Text>
                </View>
              ) : null}
              {props.bankAccount?.accountNumber ? (
                <View style={styles.paymentRow}>
                  <Text style={styles.muted}>Account No.</Text>
                  <Text style={styles.metaValue}>{props.bankAccount.accountNumber}</Text>
                </View>
              ) : null}
              {props.bankAccount?.ifsc ? (
                <View style={styles.paymentRow}>
                  <Text style={styles.muted}>IFSC</Text>
                  <Text style={styles.metaValue}>{props.bankAccount.ifsc}</Text>
                </View>
              ) : null}
              <Text style={[styles.boxLabel, { marginTop: 8 }]}>Scan to Pay</Text>
              {props.paymentQrDataUrl ? (
                <Image src={props.paymentQrDataUrl} style={styles.qrImage} />
              ) : null}
            </View>
          )}
          {showEInvoice && (
            <View style={styles.paymentBox}>
              <Text style={styles.boxLabel}>e-Invoice Verification</Text>
              <Text style={[styles.footerText, { marginTop: 2 }]}>
                IRN: {props.eInvoice!.irn}
              </Text>
              {props.eInvoice!.qrDataUrl ? (
                <Image src={props.eInvoice!.qrDataUrl} style={styles.qrImage} />
              ) : null}
            </View>
          )}

          <View style={styles.totalsBox}>
            <View style={styles.totalRow}>
              <Text style={styles.muted}>Taxable Amount</Text>
              <Text>{inr(props.taxable)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.muted}>Total Tax</Text>
              <Text>{inr(props.tax)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.muted}>Additional Charges</Text>
              <Text>{inr(props.additionalCharges)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.muted}>Discount</Text>
              <Text>- {inr(props.discountAfterTax)}</Text>
            </View>
            <View style={styles.grandRow}>
              <Text>Grand Total</Text>
              <Text>{inr(props.total)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.muted}>{props.type === "SALE" ? "Received" : "Paid"}</Text>
              <Text>{inr(props.paid)}</Text>
            </View>
            <View style={styles.balanceRow}>
              <Text style={styles.balanceLabel}>Balance Due</Text>
              <Text style={styles.balanceValue}>{inr(props.due)}</Text>
            </View>
          </View>
        </View>

        {/* Notes / Terms */}
        {(props.notes || props.termsAndConditions) && (
          <View style={styles.footerRow}>
            <View style={styles.footerCol}>
              {props.notes ? (
                <>
                  <Text style={styles.footerHeading}>Notes</Text>
                  <Text style={styles.footerText}>{props.notes}</Text>
                </>
              ) : null}
            </View>
            <View style={styles.footerCol}>
              {props.termsAndConditions ? (
                <>
                  <Text style={styles.footerHeading}>Terms &amp; Conditions</Text>
                  <Text style={styles.footerText}>{props.termsAndConditions}</Text>
                </>
              ) : null}
            </View>
          </View>
        )}

        <View style={styles.signatureArea}>
          <View style={styles.signatureLine}>
            <Text style={styles.signatureLabel}>Authorized Signature</Text>
          </View>
        </View>
      </Page>
    </Document>
  );
}
